"""
Automated daily run script for the betting model.
Can be scheduled via cron (Linux/Mac) or Task Scheduler (Windows).
"""

#!/usr/bin/env python3
import sys
import os
from pathlib import Path
from datetime import datetime
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import json

# Add parent to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from backend.api.main import betting_model, fetcher
from backend.core.betting_model import create_candidate_from_dict
from backend.data.db import db
from backend.data.sample_data import generate_sample_bets, seed_sample_data

# Configuration
CONFIG = {
    "sports": ["NBA", "NHL", "MLB", "NFL"],
    "min_ev": 7.0,
    "max_picks": 10,
    "email_enabled": False,  # Set to True and configure below to enable
    "email": {
        "smtp_server": "smtp.gmail.com",
        "smtp_port": 587,
        "sender_email": "your_email@gmail.com",
        "sender_password": "your_app_password",
        "recipient_email": "recipient@example.com"
    }
}


def log(message):
    """Log with timestamp."""
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    print(f"[{timestamp}] {message}")


def generate_daily_picks():
    """Generate today's +EV picks."""
    log("Starting daily pick generation...")
    
    today_str = datetime.now().strftime('%Y%m%d')
    all_candidates = []
    
    for sport in CONFIG["sports"]:
        log(f"Fetching {sport} games...")
        try:
            candidates = fetcher.create_candidates_from_espn(sport, today_str)
            log(f"  Found {len(candidates)} candidates from {sport}")
            all_candidates.extend(candidates)
        except Exception as e:
            log(f"  Error fetching {sport}: {e}")
    
    log(f"Total candidates: {len(all_candidates)}")
    
    # Evaluate all candidates
    evaluated = []
    for candidate_data in all_candidates:
        try:
            bet_candidate = create_candidate_from_dict(candidate_data)
            evaluated_candidate = betting_model.evaluate_candidate(bet_candidate)
            
            # Filter by EV threshold
            if evaluated_candidate.ev_pct >= CONFIG["min_ev"]:
                evaluated.append(evaluated_candidate)
        except Exception as e:
            log(f"  Error evaluating candidate: {e}")
    
    log(f"Candidates meeting {CONFIG['min_ev']}% EV threshold: {len(evaluated)}")
    
    # Rank and filter
    picks = betting_model.filter_and_rank_picks(evaluated, max_picks=CONFIG["max_picks"])
    
    log(f"Final qualified picks: {len(picks)}")
    
    return picks


def format_picks_email(picks):
    """Format picks for email notification."""
    if not picks:
        return "No qualified picks found today. The model is being selective."
    
    html = """
    <html>
    <head>
        <style>
            body { font-family: Arial, sans-serif; }
            .pick { border: 1px solid #ddd; margin: 10px 0; padding: 15px; border-radius: 5px; }
            .header { background-color: #3b82f6; color: white; padding: 10px; border-radius: 5px; }
            .ev { color: #22c55e; font-weight: bold; }
            .stake { font-size: 1.2em; font-weight: bold; }
            .footer { margin-top: 20px; font-size: 0.9em; color: #666; }
        </style>
    </head>
    <body>
        <div class="header">
            <h2>🏆 Today's +EV Betting Picks</h2>
            <p>{} picks found with {}%+ EV threshold</p>
        </div>
    """.format(len(picks), CONFIG['min_ev'])
    
    for i, pick in enumerate(picks, 1):
        html += f"""
        <div class="pick">
            <h3>{i}. {pick.sport}: {pick.event}</h3>
            <p><strong>Bet:</strong> {pick.bet_type} - {pick.selection}</p>
            <p><strong>Odds:</strong> {pick.odds:+d}</p>
            <p><strong>True Probability:</strong> {pick.true_probability*100:.1f}%</p>
            <p class="ev">EV: +{pick.ev_pct:.1f}% | Edge Score: {pick.edge_score}</p>
            <p class="stake">💰 Recommended Stake: ${pick.stake} ({pick.stake_pct}%)</p>
            <p>Max acceptable odds: {pick.max_odds}</p>
        </div>
        """
    
    html += """
        <div class="footer">
            <p>Generated by Sports Betting Model v1.0</p>
            <p>Using Kelly Criterion (20% fractional) with 7% minimum EV threshold</p>
            <p>Bets are recommendations only. Gamble responsibly.</p>
        </div>
    </body>
    </html>
    """
    
    return html


def send_email_notification(picks):
    """Send email notification with picks."""
    if not CONFIG["email_enabled"]:
        log("Email notifications disabled")
        return
    
    try:
        email_config = CONFIG["email"]
        
        msg = MIMEMultipart('alternative')
        msg['Subject'] = f"🎯 {len(picks)} +EV Picks for {datetime.now().strftime('%Y-%m-%d')}"
        msg['From'] = email_config["sender_email"]
        msg['To'] = email_config["recipient_email"]
        
        html_content = format_picks_email(picks)
        msg.attach(MIMEText(html_content, 'html'))
        
        with smtplib.SMTP(email_config["smtp_server"], email_config["smtp_port"]) as server:
            server.starttls()
            server.login(email_config["sender_email"], email_config["sender_password"])
            server.send_message(msg)
        
        log("Email notification sent successfully")
    except Exception as e:
        log(f"Failed to send email: {e}")


def save_picks_to_file(picks):
    """Save picks to JSON file for record keeping."""
    output_dir = Path(__file__).parent.parent / "data" / "daily_picks"
    output_dir.mkdir(parents=True, exist_ok=True)
    
    date_str = datetime.now().strftime('%Y-%m-%d')
    output_file = output_dir / f"picks-{date_str}.json"
    
    picks_data = {
        "date": date_str,
        "generated_at": datetime.now().isoformat(),
        "total_picks": len(picks),
        "picks": [
            {
                "bet_id": p.bet_id,
                "sport": p.sport,
                "event": p.event,
                "bet_type": p.bet_type,
                "selection": p.selection,
                "odds": p.odds,
                "true_probability": p.true_probability,
                "ev_pct": p.ev_pct,
                "stake": p.stake,
                "stake_pct": p.stake_pct,
                "edge_score": p.edge_score,
                "composite_score": p.composite_score,
                "notes": p.notes
            }
            for p in picks
        ]
    }
    
    with open(output_file, 'w') as f:
        json.dump(picks_data, f, indent=2)
    
    log(f"Picks saved to {output_file}")


def main():
    """Main daily run function."""
    log("=" * 60)
    log("DAILY BETTING MODEL RUN")
    log("=" * 60)
    
    # Generate picks
    picks = generate_daily_picks()
    
    # Save to file
    save_picks_to_file(picks)
    
    # Send notification
    send_email_notification(picks)
    
    # Print summary
    log("\n" + "=" * 60)
    log("SUMMARY")
    log("=" * 60)
    log(f"Date: {datetime.now().strftime('%Y-%m-%d')}")
    log(f"Picks Generated: {len(picks)}")
    
    if picks:
        total_stake = sum(p.stake for p in picks)
        avg_ev = sum(p.ev_pct for p in picks) / len(picks)
        log(f"Total Recommended Stake: ${total_stake:.2f}")
        log(f"Average EV: +{avg_ev:.1f}%")
        
        log("\nTop Picks:")
        for i, pick in enumerate(picks[:5], 1):
            log(f"  {i}. {pick.sport} {pick.selection} @ {pick.odds} (+{pick.ev_pct:.1f}% EV, ${pick.stake})")
    
    log("=" * 60)
    log("Run completed successfully")
    log("=" * 60)


if __name__ == "__main__":
    main()
